//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfFeedback.Client.CoWorkerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoWorkerService.ICoWorkerService")]
    public interface ICoWorkerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoWorkerService/CommitCoWorker", ReplyAction="http://tempuri.org/ICoWorkerService/CommitCoWorkerResponse")]
        PerfFeedback.BusinessService.Contract.CoWorker CommitCoWorker(PerfFeedback.BusinessService.Contract.CoWorker item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoWorkerService/CommitCoWorker", ReplyAction="http://tempuri.org/ICoWorkerService/CommitCoWorkerResponse")]
        System.Threading.Tasks.Task<PerfFeedback.BusinessService.Contract.CoWorker> CommitCoWorkerAsync(PerfFeedback.BusinessService.Contract.CoWorker item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoWorkerServiceChannel : PerfFeedback.Client.CoWorkerService.ICoWorkerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoWorkerServiceClient : System.ServiceModel.ClientBase<PerfFeedback.Client.CoWorkerService.ICoWorkerService>, PerfFeedback.Client.CoWorkerService.ICoWorkerService {
        
        public CoWorkerServiceClient() {
        }
        
        public CoWorkerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoWorkerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoWorkerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoWorkerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PerfFeedback.BusinessService.Contract.CoWorker CommitCoWorker(PerfFeedback.BusinessService.Contract.CoWorker item) {
            return base.Channel.CommitCoWorker(item);
        }
        
        public System.Threading.Tasks.Task<PerfFeedback.BusinessService.Contract.CoWorker> CommitCoWorkerAsync(PerfFeedback.BusinessService.Contract.CoWorker item) {
            return base.Channel.CommitCoWorkerAsync(item);
        }
    }
}
