//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfFeedback.CoWorkerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoWorker", Namespace="http://schemas.datacontract.org/2004/07/PerfFeedback.BusinessService.Contract")]
    [System.SerializableAttribute()]
    public partial class CoWorker : System.MarshalByRefObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoWorkerService.ICoWorkerService")]
    public interface ICoWorkerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoWorkerService/CommitCoWorker", ReplyAction="http://tempuri.org/ICoWorkerService/CommitCoWorkerResponse")]
        PerfFeedback.CoWorkerService.CoWorker CommitCoWorker(PerfFeedback.CoWorkerService.CoWorker item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoWorkerService/CommitCoWorker", ReplyAction="http://tempuri.org/ICoWorkerService/CommitCoWorkerResponse")]
        System.Threading.Tasks.Task<PerfFeedback.CoWorkerService.CoWorker> CommitCoWorkerAsync(PerfFeedback.CoWorkerService.CoWorker item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoWorkerServiceChannel : PerfFeedback.CoWorkerService.ICoWorkerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoWorkerServiceClient : System.ServiceModel.ClientBase<PerfFeedback.CoWorkerService.ICoWorkerService>, PerfFeedback.CoWorkerService.ICoWorkerService {
        
        public CoWorkerServiceClient() {
        }
        
        public CoWorkerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoWorkerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoWorkerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoWorkerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PerfFeedback.CoWorkerService.CoWorker CommitCoWorker(PerfFeedback.CoWorkerService.CoWorker item) {
            return base.Channel.CommitCoWorker(item);
        }
        
        public System.Threading.Tasks.Task<PerfFeedback.CoWorkerService.CoWorker> CommitCoWorkerAsync(PerfFeedback.CoWorkerService.CoWorker item) {
            return base.Channel.CommitCoWorkerAsync(item);
        }
    }
}
